@base=http://localhost:8000
@json=application/json
@token= 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### Suggestions - missing q (expect 422)
GET {{base}}/api/search/suggestions
Accept: {{json}}
Authorization: Bearer {{token}}

### Suggestions - files only
GET {{base}}/api/search/suggestions?q=b&type=file&limit=1
Accept: {{json}}
Authorization: Bearer {{token}}

### Suggestions - folders only
GET {{base}}/api/search/suggestions?q=r&type=folder&limit=2
Accept: {{json}}
Authorization: Bearer {{token}}

### Suggestions - all
GET {{base}}/api/search/suggestions?q=r&type=all&limit=10
Accept: {{json}}
Authorization: Bearer {{token}}

### Suggestions - limit clamp
GET {{base}}/api/search/suggestions?q=a&limit=200
Accept: {{json}}
Authorization: Bearer {{token}}

### Suggestions - search for BaoCao (should match many duplicates)
GET {{base}}/api/search/suggestions?q=BaoCao&type=file&limit=5
Accept: {{json}}
Authorization: Bearer {{token}}
