### User HTTP tests

@base=http://localhost:8000
@json=application/json
@token=12|IV7oVe7BA5HFs15B93Mja2SEhYTfBLCqaSzDwjvz0efa38d1

### Get user profile
GET {{base}}/api/user
Accept: {{json}}
Authorization: Bearer {{token}}

### Update profile
PUT {{base}}/api/user/profile
Accept: {{json}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "name": "New Name teeeee"
}

### Update password
PUT {{base}}/api/user/password
Accept: {{json}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "current_password": "12345678",
  "new_password": "111111",
  "new_password_confirmation": "111111"
}

