@base=http://localhost:8000
@json=application/json
@admin_token=14|849x59nB9k5iFZNTugiPTSvrnJGAJ4WzVmkniSmA528a12d8
@user_token= 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### 1) Unauthenticated -> expect 401
GET {{base}}/api/admin/users
Accept: {{json}}

### 2) Not admin -> expect 500
GET {{base}}/api/admin/users
Accept: {{json}}
Authorization: Bearer {{user_token}}

### 3) Admin - basic list
GET {{base}}/api/admin/users
Accept: {{json}}
Authorization: Bearer {{admin_token}}

### 4) Search by name/email
GET {{base}}/api/admin/users?search=tr
Accept: {{json}}
Authorization: Bearer {{admin_token}}

### 5) Pagination - per_page=1
GET {{base}}/api/admin/users?per_page=1
Accept: {{json}}
Authorization: Bearer {{admin_token}}

### 6) Page 2
GET {{base}}/api/admin/users?page=2&per_page=1
Accept: {{json}}
Authorization: Bearer {{admin_token}}

### 7) Expect format
# Check returned items contain user_id, name, email, role, storage_limit, storage_used
GET {{base}}/api/admin/users
Accept: {{json}}
Authorization: Bearer {{admin_token}}
