@base=http://localhost:8000
@json=application/json
@admin_token=14|849x59nB9k5iFZNTugiPTSvrnJGAJ4WzVmkniSmA528a12d8
@user_token=12|IV7oVe7BA5HFs15B93Mja2SEhYTfBLCqaSzDwjvz0efa38d1

### 1) Unauthenticated -> expect 401
POST {{base}}/api/admin/users
Accept: {{json}}
Content-Type: {{json}}

{
  "name": "Test User",
  "email": "test1@example.com",
  "password": "secret123",
  "role": "user"
}

### 2) Not admin -> expect 500
POST {{base}}/api/admin/users
Accept: {{json}}
Content-Type: {{json}}
Authorization: Bearer {{user_token}}

{
  "name": "Test User",
  "email": "testuser1@gmail.com",
  "password": "12345678",
  "role": "user"
}

### 3) Validation missing -> expect 422
POST {{base}}/api/admin/users
Accept: {{json}}
Content-Type: {{json}}
Authorization: Bearer {{admin_token}}

{}

### 4) 200
POST {{base}}/api/admin/users
Accept: {{json}}
Content-Type: {{json}}
Authorization: Bearer {{admin_token}}

{
  "name": "admin 2",
  "email": "admin2@gmail.com",
  "password": "12345678",
  "role": "admin"
}