@baseUrl = http://localhost:8000
@token = 1|MhlWTJtQq0xDfPZTZ0w6Pt0qiEIyLDuvODBmpIbJd9ff1549

### Get folder details
GET {{baseUrl}}/api/folders/7
Accept: application/json
Authorization: Bearer {{token}}
