@baseUrl = http://localhost:8000
@token = 1|2tOIy3hs20BTbzrqRdWuSbNMjk7oST9l9ftkQ06637453c2c
@parentId = 7

### Create folder at root (200)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "Folder sẽ được move tới"
}

### Create folder inside parent (200)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "Bài tập",
  "parent_folder_id": 10
}

### Missing folder_name (422)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "parent_folder_id": 1
}

### Invalid/non-owned parent (404)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "Tài liệu học kỳ 2",
  "parent_folder_id": 999999
}

### folder_name too long (422)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

### Unauthenticated — 401
POST {{baseUrl}}/api/folders
Accept: application/json