@baseUrl = http://localhost:8000
@token = 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f
@parentId = 7

### Create folder at root (200)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "Folder sẽ được move tới"
}

### Create folder inside parent (200)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "Bài tập 11",
  "parent_folder_id": 29
}

### Missing folder_name (422)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "parent_folder_id": 1
}

### Invalid/non-owned parent (500)
POST {{baseUrl}}/api/folders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "folder_name": "Tài liệu học kỳ 2",
  "parent_folder_id": 1
}

### Unauthenticated — 401
POST {{baseUrl}}/api/folders
Accept: application/json