@baseUrl = http://localhost:8000
@token = 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### 1) Happy path — authenticated user
GET {{baseUrl}}/api/folders/33/breadcrumb
Accept: application/json
Authorization: Bearer {{token}}


### 2) Unauthenticated — no token
GET {{baseUrl}}/api/folders/5/breadcrumb
Accept: application/json


### 3) Not found / Forbidden (invalid id or no access)
GET {{baseUrl}}/api/folders/999999/breadcrumb
Accept: application/json
Authorization: Bearer {{token}}

### 4) forbidden — access folder not owned by user
GET {{baseUrl}}/api/folders/1/breadcrumb
Accept: application/json
Authorization: Bearer {{token}}

// chưa test

### 4) Public link access — using token query param
GET {{baseUrl}}/api/folders/5/breadcrumb?token={{token}}
Accept: application/json

