@baseUrl = http://localhost:8000
@adminToken = 22|iCwv19Yr2MdAad2pOFGRbIhUY5uyWvhlLKyTKi7I788bf5fb
@token = 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### 1) Happy path — 200 OK (admin)
DELETE {{baseUrl}}/api/files/51/versions/63
Accept: application/json
Authorization: Bearer {{adminToken}}


### 2) Unauthenticated — 401
DELETE {{baseUrl}}/api/files/22/versions/10
Accept: application/json


### 3) Forbidden (non-admin) — 403
DELETE {{baseUrl}}/api/files/22/versions/36
Accept: application/json
Authorization: Bearer {{token}}


### 4) File not found — 404
DELETE {{baseUrl}}/api/files/999999/versions/1
Accept: application/json
Authorization: Bearer {{adminToken}}


### 5) Version not found — 404
DELETE {{baseUrl}}/api/files/51/versions/999999
Accept: application/json
Authorization: Bearer {{adminToken}}
