@baseUrl = http://localhost:8000
@token = 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### 1) Happy path — 200 OK
POST {{baseUrl}}/api/files/47/move
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "destination_folder_id": 29
}


### 2)  Happy path — 200 OK (missing destination_folder_id - stays in root)
POST {{baseUrl}}/api/files/47/move
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
}


### 3) Destination folder not found — 404
POST {{baseUrl}}/api/files/19/move
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "destination_folder_id": 999999
}


### 4) Unauthenticated — 401
POST {{baseUrl}}/api/files/4/move
Accept: application/json
Content-Type: application/json

{
    "destination_folder_id": 20
}


### 5) Not found (file) — 404
POST {{baseUrl}}/api/files/999999/move
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "destination_folder_id": 3
}


### 6) Forbidden (other user's file) — 403
# Use a token that belongs to a different user than the file owner
POST {{baseUrl}}/api/files/4/move
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "destination_folder_id": 3
}
