@baseUrl = http://localhost:8000
@token = 1|2tOIy3hs20BTbzrqRdWuSbNMjk7oST9l9ftkQ06637453c2c

### 1) Happy path — 200 OK
GET {{baseUrl}}/api/files/22/versions/35
Accept: application/json
Authorization: Bearer {{token}}


### 2) Unauthenticated — 401
GET {{baseUrl}}/api/files/12/versions/3
Accept: application/json


### 3) Forbidden / No permission — 403
# Use a token for a user who doesn't have access to file 12
GET {{baseUrl}}/api/files/16/versions/16
Accept: application/json
Authorization: Bearer {{token}}


### 4) File not found — 404
GET {{baseUrl}}/api/files/999999/versions/3
Accept: application/json
Authorization: Bearer {{token}}


### 5) Version not found — 404
GET {{baseUrl}}/api/files/22/versions/999999
Accept: application/json
Authorization: Bearer {{token}}
