@baseUrl = http://localhost:8000
@token = 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### 1) Happy path — download specific version (authenticated)
GET {{baseUrl}}/api/files/51/versions/63/download
Accept: application/json
Authorization: Bearer {{token}}


// CHưa test trường hợp download public link
### 2) Public link download by token (public)
GET {{baseUrl}}/api/files/123/versions/3/download?token=PUBLIC_TOKEN
Accept: application/json


### 3) Unauthenticated (no token)
GET {{baseUrl}}/api/files/123/versions/3/download
Accept: application/json


### 4) Version not found
GET {{baseUrl}}/api/files/51/versions/999999/download
Accept: application/json
Authorization: Bearer {{token}}


### 5) Forbidden (no permission)
GET {{baseUrl}}/api/files/6/versions/16/download
Accept: application/json
Authorization: Bearer {{token}}
