@base=http://localhost:8000
@json=application/json
@token=4|pTEv0RhFJfFFSUTkpBPavtlp3ka6bboTq1o4kBwb3477d2ec

### 1) Unauthenticated -> expect 401
GET {{base}}/api/files
Accept: {{json}}

### 2) Basic - list first page
GET {{base}}/api/files
Accept: {{json}}
Authorization: Bearer {{token}}

### 3) Filter by extension (pdf)
GET {{base}}/api/files?filter[extension]=pdf
Accept: {{json}}
Authorization: Bearer {{token}}

### 4) Filter by size_min
GET {{base}}/api/files?filter[size_min]=1000
Accept: {{json}}
Authorization: Bearer {{token}}

### 5) Filter by size range
GET {{base}}/api/files?filter[size_min]=1000&filter[size_max]=5000000
Accept: {{json}}
Authorization: Bearer {{token}}

### 6) Filter by created date range
GET {{base}}/api/files?filter[date_from]=2025-10-01&filter[date_to]=2025-10-31
Accept: {{json}}
Authorization: Bearer {{token}}

### 7) Filter shared = true
GET {{base}}/api/files?filter[shared]=true
Accept: {{json}}
Authorization: Bearer {{token}}

### 8) Sort by name desc
GET {{base}}/api/files?sort=name,desc
Accept: {{json}}
Authorization: Bearer {{token}}

### 9) Sort by size asc
GET {{base}}/api/files?sort=size,asc
Accept: {{json}}
Authorization: Bearer {{token}}

### 10) Pagination
GET {{base}}/api/files?page=2&per_page=5
Accept: {{json}}
Authorization: Bearer {{token}}

### 11) Combined filters
GET {{base}}/api/files?filter[extension]=pdf&filter[shared]=true&sort=created_at,desc&page=1&per_page=10
Accept: {{json}}
Authorization: Bearer {{token}}
