### Auth HTTP tests

@base=http://localhost:8000
@json=application/json
@token=1|FKJUysJkPI48LaecdyjJ7NOooVfzGqXHQFsKUQ1i0c6be6a9

### Register
POST {{base}}/api/auth/register
Accept: {{json}}
Content-Type: {{json}}

{
  "name": "tandd",
  "email": "tandd@gmail.com",
  "password": "12345678",
  "password_confirmation": "12345678",
  "device_name": "api"
}

### Login
POST {{base}}/api/auth/login
Accept: {{json}}
Content-Type: {{json}}

{
  "email": "tandd@gmail.com",
  "password": "12345678",
  "device_name": "api"
}

### Me (requires token)
GET {{base}}/api/auth/me
Accept: {{json}}
Authorization: Bearer {{token}}

### Logout
POST {{base}}/api/auth/logout
Accept: {{json}}
Authorization: Bearer {{token}}

### Logout All
POST {{base}}/api/auth/logout-all
Accept: {{json}}
Authorization: Bearer {{token}}

