@baseUrl = http://localhost:8000
@token = 20|y4xWD4RXu0vkC19dloofc7Th167rQyMTj71KHxwjd55bcd1f

### 1) Happy path — 200 OK
POST {{baseUrl}}/api/bulk/bulk-delete
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "file_ids": [53],
  "folder_ids": [34]
}

### 2) Validation fail — 422 (no payload)
POST {{baseUrl}}/api/bulk/bulk-delete
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### 3) Unauthenticated — 401
POST {{baseUrl}}/api/bulk/bulk-delete
Accept: application/json
Content-Type: application/json

{
  "file_ids": [1]
}
