@baseUrl = http://localhost:8000
@email = trinnn@gmail.com
@password = 12345678
@token = 5|hS5pmMxduzqfcrZj7QRkCSriPm60fHGCKMXOz5Ozcedf37da
### @name login
POST {{baseUrl}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "trinnn@gmail.com",
  "password": "12345678",
  "device_name": "cli"
}


### @name me
### Me (requires Bearer token)
GET {{baseUrl}}/api/auth/me
Accept: application/json
Authorization: Bearer {{token}}

### @name register
### Register new account (and capture token)
POST {{baseUrl}}/api/auth/register
Accept: application/json
Content-Type: application/json

{"name":"New User","email":"{{email}}","password":"{{password}}","password_confirmation":"{{password}}","device_name":"cli"}

### Logout current token
POST {{baseUrl}}/api/auth/logout
Accept: application/json
Authorization: Bearer {{token}}

### Logout all tokens
POST {{baseUrl}}/api/auth/logout-all
Accept: application/json
Authorization: Bearer {{token}}


